"""
Do not edit this file, change the setting database table instead.
"""
# Directories
DATA_DIRECTORY = 'data'
DOCUMENT_DIRECTORY = 'docs'
# TEMPLATE_DIRECTORY = 'templates'
# Files
BASE_TEMPLATE = 'base.html'
FRONT_SLUG = '~'
SLUG_404 = '!404'
MENU_INCLUDE_FRONT_NAME = True
MENU_FRONT_NAME_SEPARATOR = ' | '
DOC_CONTAINER_ID = 'legalazy-content'
KEEP_DOCUMENT_STYLES = True
# Parse the OpenDocument to find publicly available font families
AUTODETECT_EXTERNAL_FONTS = True
# 3rd party
GOOGLE_FONTS_PATTERN = "https://fonts.googleapis.com/css?family={}"
GOOGLE_FONTS_WHITESPACE = '+'
